// The shared engine, the same modules the CLI runs. Synced into ../core by scripts/sync-core.mjs.
export { runScanPipeline } from "../core/pipeline.js";
export { spaceMap, pickUnits } from "../core/map.js";
export { Gemini, explainFolders } from "../core/gemini.js";
export { makeHeader, writeDb, readDb } from "../core/db.js";
export { isSafeToRemove, removePermanently, freeBytes } from "../core/remove.js";
export { holdItems, listHeld, restoreHeld, purgeHeld, HOLD_DIR } from "../core/hold.js";
export { buildScript, writeRemovalScript, desktopDir } from "../core/script.js";
export { loadPolicy, isExcludedByPolicy, POLICY_FILE } from "../core/policy.js";
export { audit, readAudit, AUDIT_FILE } from "../core/audit.js";
export { DEFAULTS, DATA_DIR, loadEnv } from "../core/config.js";
export { analyzeFolder, rulePlan, aiPlan, applyPlan, undoOrganize, listJournals, organizeBlocked, cleanFolderName, LANGUAGE_NAMES } from "../core/organize.js";
export { readGraph, readLevel, isInside } from "../core/graph.js";
export { buildNetwork } from "../core/network.js";
export { intelStatus, updateIntel } from "../core/intel.js";
export { yaraStatus, installYara, updateYaraRules, scanYara } from "../core/yara.js";
export { examine, judge, isCandidate } from "../core/threat-rules.js";
export { notLocal } from "../core/walk.js";
export { loadIntel, hostsIn } from "../core/intel.js";
export { checkSignatures } from "../core/reputation.js";
export { listAutostart } from "../core/autostart.js";
export { runThreatScan, saveThreatScan, readThreatScan } from "../core/protect.js";
export { quarantineFile, listQuarantine, restoreQuarantined, deleteQuarantined } from "../core/quarantine.js";
export { loadBlocklist, trustHash, defenderStatus, virusTotal, malwareBazaar, virusTotalPage } from "../core/reputation.js";
